### ISSUE TITLE
Center scrollview?

### ISSUE THREAD

**Issue by haleyngonadi** [gydmercy/GFPageSlider#1]
Thank you for sharing this It is exactly what I needed and extremely useful. My question is: I have only two tabs in the scrollview with the menu item. This means everything is to the left, with a large space to the right. I'm wondering if it is possible to center the items instead? Thanks!

**Comment by gydmercy** [comment]
try "pageSlider.menuNumberPerPage = 2;"  :-)

**Comment by haleyngonadi** [comment]
That did the trick, thank you!
